version: "3"
services:

  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks: 
      - frontend
    deploy:
      replicas: 1
  
  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    networks: 
      - backend
  
  vote:
    image: dockersamples/examplevotingapp_vote:after
    ports:
      - 5000:80
    networks:
      - frontend
    depends_on:
      - redis
    deploy: 
      replicas: 2

  result:
    image: dockersamples/examplevotingapp_result:after
    ports:
      - 5001:80
    networks:
      - backend
    depends_on:
      - db
    deploy:
      replicas: 1

  worker:
    image: dockersamples/examplevotingapp_worker
    networks: 
      - frontend
      - backend
    deploy:
      mode: replicated
      replicas: 1
  
  visualizer:
    image: dockersamples/visualizer:stable
    ports: 
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock://var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

networks: 
  frontend:
  backend:

volumes:
  db-data:
    

    
